// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEQxEhPXEumUhCn8yr0mC3kgmY3Rg-N-s',
    appId: '1:172696060119:web:11772a23c769e6b0dbf092',
    messagingSenderId: '172696060119',
    projectId: 'vinnote-4747a',
    authDomain: 'vinnote-4747a.firebaseapp.com',
    storageBucket: 'vinnote-4747a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXfBCmaN27oMAzkAEl-Jdnjtl_iuyQJBE',
    appId: '1:172696060119:android:f849b994b2b94829dbf092',
    messagingSenderId: '172696060119',
    projectId: 'vinnote-4747a',
    storageBucket: 'vinnote-4747a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmQH6tZA7OgZfy1jNePBbzkJRAv2xOlJM',
    appId: '1:172696060119:ios:ab8f2e7aeb918e77dbf092',
    messagingSenderId: '172696060119',
    projectId: 'vinnote-4747a',
    storageBucket: 'vinnote-4747a.appspot.com',
    iosBundleId: 'com.vinno.vinno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmQH6tZA7OgZfy1jNePBbzkJRAv2xOlJM',
    appId: '1:172696060119:ios:1f009e721017ce3adbf092',
    messagingSenderId: '172696060119',
    projectId: 'vinnote-4747a',
    storageBucket: 'vinnote-4747a.appspot.com',
    iosBundleId: 'com.vinno.vinno.RunnerTests',
  );
}
